[package]
name = "machine_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = ["dynamic_linking"] }
bevy_fly_camera = "0.16.0"
bevy_mqtt = "0.7.1"
bevy_rapier3d = { version = "0.31.0", features = ["debug-render-3d"] }
